### ISSUE TITLE
Handling User Account Authentication

### ISSUE THREAD

**Issue by hanwenzhang123** [BUMETCS673/project-team-2#16]
## What we did
- store user registration information in the database
  - username, email, hash password using bcrypt password
  - adding validation check before passing to the database
    - username at least 6 characters
    - password regex and password confirm check

- add access restriction on some URL patterns
  - any URL with pattern `/solosavings/**` do not need to be authenticated
  - any request with pattern `/api/login` do not need to be authenticated
  - any request with pattern `/api/register` do not need to be authenticated
  - any URL with pattern `/dashboard/**` needs to be authenticated
  - any request with pattern `/api/**` other than login or register needs to be authenticated

## User Registration
![Screenshot 2023-09-24 at 1 54 50 PM](https://github.com/BUMETCS673/project-team-2/assets/79280844/168817f5-76d6-41e0-bb32-d30e671e09db)

## To do List
- [x] check if email exists in the database before registration
- [x] check if the password is matching when the user login page
- [x] fix the security `/api/**` path authentication
- [x] fix the security `/dashboard/**` path authentication
- [x] jwt management to keep the user logged in state
- [x] user log-in state to access to user's personal dashboard
- [x] user log-out functionality which remove jwt and limit access
- [x] unit testing to cover all services

**Comment by WAftring** [comment]
Still pending user logout functionality.

**Comment by hanwenzhang123** [comment]
I believe we have covered everything, close this issue.
